apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloreact
  labels:
    app: helloreact
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloreact
  template:
    metadata:
      labels:
        app: helloreact
    spec:
      containers:
      - name: helloreact
        image: iamluckie/helloreact
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: helloreact-svc
spec:
  selector:
    app: helloreact
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000



